services:
    sorteandoaqui:
        build:
            context: ./devops/development-instance
            dockerfile: Dockerfile
        image: ${APP_SERVICE:-sorteandoaqui}-app
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - ${APP_PORT:-80}:80
            - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
            - ${XDEBUG_PORT:-9003}:${XDEBUG_PORT:-9003}
        environment:
            DB_HOST: ${DB_HOST:-mysql}
            DB_USER: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            IGNITION_LOCAL_SITES_PATH: ${PWD}
            XDEBUG_MODE: ${SAIL_XDEBUG_MODE:-develop,debug,coverage}
            XDEBUG_CONFIG: ${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}
        volumes:
            - .:/var/www
        networks:
            - sorteandoaqui-network
        depends_on: ["mysql", "redis", "minio", "mailpit", "soketi"]
    mysql:
        image: mysql:8.4
        ports:
            - ${FORWARD_DB_PORT:-3306}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        command: >
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
        volumes:
            - sorteandoaqui-mysql-vol:/var/lib/mysql
            - ./devops/development-instance/mysql:/docker-entrypoint-initdb.d
        networks:
            - sorteandoaqui-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: redis:alpine
        ports:
            - ${FORWARD_REDIS_PORT:-6379}:6379
        volumes:
            - sorteandoaqui-redis-vol:/data
        networks:
            - sorteandoaqui-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    minio:
        image: minio/minio:latest
        ports:
            - ${FORWARD_MINIO_PORT:-9000}:9000
            - ${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900
        environment:
            MINIO_ROOT_USER: ${AWS_SECRET_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
        volumes:
            - sorteandoaqui-minio-vol:/data
        networks:
            - sorteandoaqui-network
        command: "minio server /data --console-address :8900"
        healthcheck:
            test: ["CMD", "mc", "ready", "local"]
            retries: 3
            timeout: 5s
    mailpit:
        image: axllent/mailpit:latest
        ports:
            - ${FORWARD_MAILPIT_PORT:-1025}:1025
            - ${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025
        networks:
            - sorteandoaqui-network
    soketi:
        image: quay.io/soketi/soketi:latest-16-alpine
        environment:
            SOKETI_DEBUG: ${SOKETI_DEBUG:-1}
            SOKETI_METRICS_SERVER_PORT: 9601
            SOKETI_DEFAULT_APP_ID: ${PUSHER_APP_ID}
            SOKETI_DEFAULT_APP_KEY: ${PUSHER_APP_KEY}
            SOKETI_DEFAULT_APP_SECRET: ${PUSHER_APP_SECRET}
        ports:
            - ${PUSHER_PORT:-6001}:6001
            - ${PUSHER_METRICS_PORT:-9601}:9601
        networks:
            - sorteandoaqui-network
networks:
    sorteandoaqui-network:
        driver: bridge
volumes:
    sorteandoaqui-mysql-vol:
        driver: local
    sorteandoaqui-redis-vol:
        driver: local
    sorteandoaqui-minio-vol:
        driver: local
